spring:
  application:
    name: Khagel
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true #http://localhost:8080/h2-console
  liquibase:
    change-log: classpath:changelog/db-changelog.xml
    enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null